#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidTunnel.Resource", IsApplication=true)]

namespace AndroidTunnel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addClient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int addClientDisable = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backrepeat = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttonFocus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int circle_green_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int circle_red_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int circle_white = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int circle_yellow_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int circle_yellow_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int clients = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int clientsDisable = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int exit = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int header = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int log = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int logDisable = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int LogTab = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int monobrickIcon64 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int settings = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int settingsDisable = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int SettingsTab = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int startDark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int startWhite = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int stopDark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int stopWhite = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int toastBorder = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int Client_list = 2131034114;
			
			// aapt resource value: 0x7f050019
			public const int bluetoothDevice = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int client_list_item = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int connectLight = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int connectStatus = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int connectToClientButton = 2131034126;
			
			// aapt resource value: 0x7f05001e
			public const int frameRate = 2131034142;
			
			// aapt resource value: 0x7f050005
			public const int image_item = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int info = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int linear_text = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int list_view = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int log = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int logScrollView = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int logSeperator = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int option_connect = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int option_exit = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int option_start_stop = 2131034133;
			
			// aapt resource value: 0x7f05001a
			public const int rtspPort = 2131034138;
			
			// aapt resource value: 0x7f05000b
			public const int separator = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int settingsButton = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int smallcameraview = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int startButton = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int statusSeperator = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int streamingLight = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int streamingStatus = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int text_bottom = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int text_top = 2131034119;
			
			// aapt resource value: 0x7f050020
			public const int toast_image = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int toast_layout_root = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int toast_text = 2131034145;
			
			// aapt resource value: 0x7f050018
			public const int tunnelPort = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int videoPort = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int videoQuality = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int videoResolution = 2131034140;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BtDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CameraView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClientList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ClientListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Log = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int OptionMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int toast = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
