#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("OmniBotRemote.Resource", IsApplication=true)]

namespace OmniBotRemote
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int pressed_monobrick = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_monobrick = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_monobrick = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_monobrick = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_monobrick = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_monobrick = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_monobrick = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ani0 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ani1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ani10 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ani2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ani3 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ani4 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ani5 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ani6 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ani7 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ani8 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ani9 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int aniGray = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int animation = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int backrepeat = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bluetooth_connected = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bluetooth_searching = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int btn_cab_done_default_monobrick = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int btn_cab_done_focused_monobrick = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int btn_cab_done_monobrick = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int btn_cab_done_pressed_monobrick = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int cab_background_bottom_monobrick = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int cab_background_top_monobrick = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int cancel = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int circle = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int discard = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int download = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int gray = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int help = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_action_bluetooth = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_action_bluetooth_connected = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_action_bulb = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_action_file = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_action_hdd = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_action_machine = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_action_sdcard = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_stock = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_action_work = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int list_focused_monobrick = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int menu_dropdown_panel_monobrick = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int on_off = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int picture = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int play = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int pressed_background_monobrick = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int progress_bg_monobrick = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int progress_horizontal_monobrick = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int progress_primary_monobrick = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int progress_secondary_monobrick = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int refresh = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int s01 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int s02 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int s03 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int s04 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int s05 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int s06 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int s07 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int s08 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int s09 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int s10 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int s11 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int s12 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int s13 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int s14 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int s15 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int s16 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int s17 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int s18 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int s19 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int s20 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int seekbarProgress = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int seekbarProgressBg = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int selectable_background_monobrick = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int SensorGrey = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int settings = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int sliderBg = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int sliderButton = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int sliderFill = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int spinner_ab_default_monobrick = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int spinner_ab_disabled_monobrick = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int spinner_ab_focused_monobrick = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int spinner_ab_pressed_monobrick = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int spinner_background_ab_monobrick = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int startDark = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int stop = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int stopDark = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int tab_indicator_ab_monobrick = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int tab_selected_focused_monobrick = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int tab_selected_monobrick = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int tab_selected_pressed_monobrick = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int tab_unselected_focused_monobrick = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int tab_unselected_monobrick = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int tab_unselected_pressed_monobrick = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int toastBorder = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int upload = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int volume_on = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int YRani1 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int YRani10 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int YRani2 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int YRani3 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int YRani4 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int YRani5 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int YRani6 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int YRani7 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int YRani8 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int YRani9 = 2130837615;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070012
			public const int SensorScrollView = 2131165202;
			
			// aapt resource value: 0x7f070031
			public const int additionalMotor = 2131165233;
			
			// aapt resource value: 0x7f070006
			public const int angleLabel = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int angleTextView = 2131165191;
			
			// aapt resource value: 0x7f07002b
			public const int bluetoothDevice = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int brickType = 2131165228;
			
			// aapt resource value: 0x7f070005
			public const int check = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int circle = 2131165196;
			
			// aapt resource value: 0x7f070038
			public const int delete = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int download = 2131165241;
			
			// aapt resource value: 0x7f070002
			public const int fileName = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int fileSize = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int fileType = 2131165187;
			
			// aapt resource value: 0x7f070032
			public const int fragment_container = 2131165234;
			
			// aapt resource value: 0x7f07002f
			public const int leftMotor = 2131165231;
			
			// aapt resource value: 0x7f070001
			public const int list_image = 2131165185;
			
			// aapt resource value: 0x7f07003d
			public const int menuConnection = 2131165245;
			
			// aapt resource value: 0x7f07003c
			public const int menuFormat = 2131165244;
			
			// aapt resource value: 0x7f07003a
			public const int menuRefresh = 2131165242;
			
			// aapt resource value: 0x7f07003e
			public const int menuSettings = 2131165246;
			
			// aapt resource value: 0x7f07003b
			public const int menuUpload = 2131165243;
			
			// aapt resource value: 0x7f070017
			public const int readButton1 = 2131165207;
			
			// aapt resource value: 0x7f07001d
			public const int readButton2 = 2131165213;
			
			// aapt resource value: 0x7f070023
			public const int readButton3 = 2131165219;
			
			// aapt resource value: 0x7f070029
			public const int readButton4 = 2131165225;
			
			// aapt resource value: 0x7f070030
			public const int rightMotor = 2131165232;
			
			// aapt resource value: 0x7f070018
			public const int sayButton1 = 2131165208;
			
			// aapt resource value: 0x7f07001e
			public const int sayButton2 = 2131165214;
			
			// aapt resource value: 0x7f070024
			public const int sayButton3 = 2131165220;
			
			// aapt resource value: 0x7f07002a
			public const int sayButton4 = 2131165226;
			
			// aapt resource value: 0x7f07000d
			public const int seekBar = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int seekLabel = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int seekTextView = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int sensor1Button = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int sensor2Button = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int sensor3Button = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int sensor4Button = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int sensorName1 = 2131165203;
			
			// aapt resource value: 0x7f070019
			public const int sensorName2 = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int sensorName3 = 2131165215;
			
			// aapt resource value: 0x7f070025
			public const int sensorName4 = 2131165221;
			
			// aapt resource value: 0x7f070014
			public const int sensorSpinner1 = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int sensorSpinner2 = 2131165210;
			
			// aapt resource value: 0x7f070020
			public const int sensorSpinner3 = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int sensorSpinner4 = 2131165222;
			
			// aapt resource value: 0x7f070016
			public const int sensorValue1 = 2131165206;
			
			// aapt resource value: 0x7f07001c
			public const int sensorValue2 = 2131165212;
			
			// aapt resource value: 0x7f070022
			public const int sensorValue3 = 2131165218;
			
			// aapt resource value: 0x7f070028
			public const int sensorValue4 = 2131165224;
			
			// aapt resource value: 0x7f070008
			public const int speedLabel = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int speedTextView = 2131165193;
			
			// aapt resource value: 0x7f070036
			public const int start = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int stop = 2131165239;
			
			// aapt resource value: 0x7f070000
			public const int thumbnail = 2131165184;
			
			// aapt resource value: 0x7f070034
			public const int toast_image = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int toast_layout_root = 2131165235;
			
			// aapt resource value: 0x7f070035
			public const int toast_text = 2131165237;
			
			// aapt resource value: 0x7f070015
			public const int valueLabel1 = 2131165205;
			
			// aapt resource value: 0x7f07001b
			public const int valueLabel2 = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int valueLabel3 = 2131165217;
			
			// aapt resource value: 0x7f070027
			public const int valueLabel4 = 2131165223;
			
			// aapt resource value: 0x7f07002d
			public const int vehicleAngleOffset = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int vehicleMailbox = 2131165230;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int sensor = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int tab = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int toast = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int file = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int vehicle = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int ActionBar_Solid_Monobrick = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ActionBar_Transparent_Monobrick = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int ActionBarTabStyle_Monobrick = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int ActionButton_CloseMode_Monobrick = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int DropDownListView_Monobrick = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int DropDownNav_Monobrick = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int PopupMenu_Monobrick = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ProgressBar_Monobrick = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Monobrick = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int Theme_Monobrick_Widget = 2131034121;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
